### ISSUE TITLE
Slow Query: attestations

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#4357]
```
00:02:08.964 WALTZ.PERFORMANCE - Slow SQL executed in 6 seconds
com.khartec.waltz.service.SlowQueryListener$SQLPerformanceWarning: (
  select 
    'ATTESTATION' [kind], 
    count(*) [count]
  from [attestation_instance]
    join [attestation_instance_recipient]
    on [attestation_instance_recipient].[attestation_instance_id] = [attestation_instance].[id]
  where (
    [attestation_instance_recipient].[user_id] = 'xx@yy.com'
    and [attestation_instance].[attested_at] is null
  )
)
union (
  select 
    'SURVEY_INSTANCE' [kind], 
    count(*) [count]
  from [survey_instance]
    join [survey_instance_recipient]
    on [survey_instance_recipient].[survey_instance_id] = [survey_instance].[id]
    join [person]
    on [person].[id] = [survey_instance_recipient].[person_id]
  where (
    [person].[email] = 'xx@yy.com'
    and [survey_instance].[original_instance_id] is null
    and (
      [survey_instance].[status] = 'NOT_STARTED'
      or [survey_instance].[status] = 'IN_PROGRESS'
    )
  )
)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:3756)
	at com.khartec.waltz.data.notification.NotificationDao.findNotificationsByUserId(NotificationDao.java:83)
	at com.khartec.waltz.service.notification.NotificationService.findNotificationsByUserId(NotificationService.java:47)
...
```

**Comment by davidwatkins73** [comment]
Very few indexes on any of the involved tables.

**Comment by rovats** [comment]
Also change `union` to `unionAll`, shouldn't make a big different though.
