### ISSUE TITLE
DisallowAnonymousFilter: JWT algorithm mismatch

### ISSUE THREAD

**Issue by rovats** [finos/waltz#4952]
Using DisallowAnonymousFilter throws an error:
```
com.auth0.jwt.exceptions.AlgorithmMismatchException: The provided Algorithm doesn't match the one defined in the JWT's Header.
	at com.auth0.jwt.JWTVerifier.verifyAlgorithm(JWTVerifier.java:393)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:385)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:370)
	at com.khartec.waltz.web.endpoints.auth.DisallowAnonymousFilter.handle(DisallowAnonymousFilter.java:62)
```

Probably needs this fix:

https://github.com/finos/waltz/pull/2542/files#diff-47dcba1151acd6dbe74a11adbfed9c38

**Comment by davidwatkins73** [comment]
Will take a look.  Thanks for the report.

**Comment by davidwatkins73** [comment]
Just tried enabling this (in `Main` via a `before(...)` intercept) and it seems to work.  Although the class is kind of useless as you can't subsequently log on.  Suspect we need a standalone entry point for a 'locked down' Waltz which forces users to authenticate first. 

What are you trying to achieve with this filter ?

**Comment by rovats** [comment]
Was just trying it out in case we need a locked down Waltz.
I think the error might happen if there was an existing `HS512` token from a previous session.

You're right, for this to be useful, we need a standalone login page of sorts in case this filter is enabled.
I think that will be a good addition, in case anonymous users are not allowed for some installations (we _might_ need to do it here).

**Comment by davidwatkins73** [comment]
y, and if we ever do a SaaS version we need something more robust.
