### ISSUE TITLE
Exception on server env counts

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#5153]
```
ERROR com.khartec.waltz.web.Main - Exception: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap') / java.lang.ClassCastException
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at com.khartec.waltz.data.server_information.ServerInformationDao.lambda$calculateEnvironmentStats$6(ServerInformationDao.java:300)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
```

**Comment by davidwatkins73** [comment]
Re-opening as it is re-createable  in postgres
