### ISSUE TITLE
DB error on viewing application complexity section

### ISSUE THREAD

**Issue by mharward-gr** [finos/waltz#6315]
### Description

We recently added complexity ratings, and we have been finding that they aren't showing up in the Application Complexity pane for organisational units. Looking at our logs we are seeing an error.

Database: PostgreSQL 11.17

### Waltz Version

waltz:1.45

### Steps to Reproduce

1. Have added complexity ratings to applications
2. Open organisational unit which has associated applications
3. Either click 'Application Complexity' in the side bar or find Complexity summary and click on 'Click to open related section'
4. See Application Complexity section with details of complexity ratings
...

### Expected Result

In the Application Complexity section, see a summary of the complexity ratings for a selected complexity kind.

### Actual Result

No content shows in Application Complexity section.

The following error is in the logs:

```
09:24:19.673 [http-nio-8080-exec-337] WARN  c.zaxxer.hikari.pool.ProxyConnection - HikariPool-1 - Connection org.postgresql.jdbc.PgConnection@39fb2980 marked as broken because of SQLSTATE(0A000), ErrorCode(0)
org.postgresql.util.PSQLException: ERROR: OVER is not supported for ordered-set aggregate percentile_cont
  Position: 239
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3956)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:485)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:654)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:659)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2889)
	at org.finos.waltz.data.complexity.ComplexityDao.getAverageAndTotalAndMedianScoreByKindAndSelector(ComplexityDao.java:148)
	at org.finos.waltz.service.complexity.ComplexityService.getComplexitySummaryForSelector(ComplexityService.java:61)
	at org.finos.waltz.web.endpoints.api.ComplexityEndpoint.lambda$register$3(ComplexityEndpoint.java:73)
	at org.finos.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$1(EndpointUtilities.java:107)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:885)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
09:24:19.674 [http-nio-8080-exec-337] ERROR org.finos.waltz.web.Main - Generic Exception: null / java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.jooq.impl.DefaultExecuteContext.exception(DefaultExecuteContext.java:735)
	at org.finos.waltz.service.SpringExceptionTranslationExecuteListener.exception(SpringExceptionTranslationExecuteListener.java:22)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:274)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:386)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:502)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:471)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:485)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:654)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:659)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2889)
	at org.finos.waltz.data.complexity.ComplexityDao.getAverageAndTotalAndMedianScoreByKindAndSelector(ComplexityDao.java:148)
	at org.finos.waltz.service.complexity.ComplexityService.getComplexitySummaryForSelector(ComplexityService.java:61)
	at org.finos.waltz.web.endpoints.api.ComplexityEndpoint.lambda$register$3(ComplexityEndpoint.java:73)
	at org.finos.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$1(EndpointUtilities.java:107)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:885)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by davidwatkins73** [comment]
Thanks for the detail bug report.  We've got a fix ready on a (linked) PR.  Need to double check tomorrow that this doesn't cause a regression on sql server.  Assuming all ok it will be in the build later that day.

**Comment by mharward-gr** [comment]
That's perfect, thank you David

**Comment by mharward-gr** [comment]
Fix looks good on our end, thank you David.
